export enum Opcodes {
    DISCONNECT = 0,
    AUTHENTICATE = 1,
    JOIN_ROOM = 2,
    LEAVE_ROOM = 3,
    CREATE_ROOM = 4,
    ADD_USER = 5,
    REMOVE_USER = 6,
    PLAYER_STATE = 7,
    SEND_MESSAGE = 8,
    QUEUE_ADD = 9,
    QUEUE_REMOVE = 10,
    VIDEO_SET = 11,
    VIDEO_END = 12,
    VIDEO_SKIP = 13,
    ROOM_JOIN_REQUEST = 14,
    SET_ROOM_TYPE = 15,
    DISPATCH_CONTROL = 16
}
